./floorplanning n10.fp -c
./floorplanning n10.fp -w
./floorplanning n10.fp -a
./floorplanning n30.fp -c
./floorplanning n30.fp -w
./floorplanning n30.fp -a
./floorplanning n50.fp -c
./floorplanning n50.fp -w
./floorplanning n50.fp -a
./floorplanning n100.fp -c
./floorplanning n100.fp -w
./floorplanning n100.fp -a
./floorplanning n200.fp -c
./floorplanning n200.fp -w
./floorplanning n200.fp -a
./floorplanning n300.fp -c
./floorplanning n300.fp -w
./floorplanning n300.fp -a